packages:
  - 'app'
  - 'lib/*'
  - '../../../../domains/radroots/lib/crates/events_codec_wasm/pkg'
  - '../../../../domains/radroots/lib/crates/replica_db_wasm/pkg'
  - '../../../../domains/radroots/lib/crates/replica_sync_wasm/pkg'
  - '../../../../domains/radroots/sdk/packages/*'
