CREATE TABLE IF NOT EXISTS location_gcs (
    id CHAR(36) PRIMARY KEY NOT NULL UNIQUE CHECK(length(id) = 36),
    created_at DATETIME NOT NULL CHECK(length(created_at) = 24),
    updated_at DATETIME NOT NULL CHECK(length(updated_at) = 24),
    lat REAL NOT NULL,
    lng REAL NOT NULL,
    geohash TEXT,
    tag_0 TEXT,
    label TEXT,
    area REAL,
    elevation INTEGER,
    soil TEXT,
    climate TEXT,
    gc_id TEXT,
    gc_name TEXT,
    gc_admin1_id TEXT,
    gc_admin1_name TEXT,
    gc_country_id TEXT,
    gc_country_name TEXT
);