CREATE TABLE IF NOT EXISTS trade_product (
    id CHAR(36) PRIMARY KEY NOT NULL UNIQUE CHECK(length(id) = 36),
    created_at DATETIME NOT NULL CHECK(length(created_at) = 24),
    updated_at DATETIME NOT NULL CHECK(length(created_at) = 24),
    key TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    process TEXT NOT NULL,
    lot TEXT NOT NULL,
    profile TEXT NOT NULL,
    year INTEGER NOT NULL,
    qty_amt INTEGER NOT NULL,
    qty_unit CHAR(4) NOT NULL,
    qty_label TEXT,
    qty_avail INTEGER,
    price_amt REAL NOT NULL,
    price_currency CHAR(3) NOT NULL,
    price_qty_amt INTEGER NOT NULL,
    price_qty_unit CHAR(4) NOT NULL,
    notes TEXT
);